name: 'Linear Auto Task'
description:
  'Create repeating issues in Linear with GitHub Actions and TypeScript.'
author: 'Nicholas Ramkissoon'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'check-square'
  color: 'purple'

# Define your inputs here.
inputs:

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
